[package]
name = "horcrux"
version = "0.1.0"
authors = ["Dwarkesh Patel <dwarkesh.sanjay.patel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"